#!/usr/bin/sh

echo "We will be running some post install scripts to tweak a few things"

# To toggle fn lock on boot
read -p "Do you want to turn off function lock? (y/n) " fnlock
if [ ${fnlock,,} = "y" ]; then
    echo "options asus_wmi fnlock_default=N" | sudo tee -a /etc/modprobe.d/alsa-base.conf
    read -r -s -p $'Function lock has been disabled. Press enter to continue...'
fi

echo

read -r -s -p $'All done.'